const globalNav = [
  { id: "start", label: "Start", icon: "S" },
  { id: "notifications", label: "Notifications", icon: "N" },
  { id: "campaigns", label: "Campaigns", icon: "C" },
  { id: "insights", label: "Insights", icon: "I" },
  { id: "creator-scouting", label: "Creator scouting", icon: "Sc" },
  { id: "trend-exploration", label: "Trend Exploration", icon: "T" },
  { id: "creator-calculator", label: "Creator calculator", icon: "Ca" },
];

const entityItems = [
  { id: "overview", label: "Overview", meta: "Creator profile" },
  { id: "statistics", label: "Instagram", meta: "@andrea\nnorrman" },
  { id: "content", label: "Content", meta: "Library and results" },
];

const statCards = [
  ["Followers", "124.7K", "+3.1% vs. cohort"],
  ["Activations", "18", "+2 ongoing"],
  ["CPM SEK", "176", "118 benchmark"],
  ["Avg. Views", "38.5K", "+12% MoM"],
  ["View rate", "30.9%", "24.3% benchmark"],
  ["Avg. R. views", "63.4K", "+9.7%"],
  ["R. view rate", "50.8%", "41.2% benchmark"],
  ["Avg. S. views", "16.2K", "+4.4%"],
  ["S. view rate", "13.0%", "10.7% benchmark"],
  ["Engagements", "7.8K", "+11.6%"],
  ["Engagement rate", "6.2%", "4.8% benchmark"],
  ["Viewers eng. rate", "10.6%", "6.3% benchmark"],
  ["Avg. likes", "5.9K", "+8.2%"],
  ["Avg. comm.", "118", "+1.1%"],
  ["Avg. shares", "316", "+18.0%"],
  ["Avg. saves", "492", "+14.2%"],
];

const campaigns = {
  previous: [
    {
      id: "CMP-1189",
      title: "Nordic Skin Recovery Launch",
      range: "Aug 12, 2025 - Sep 02, 2025",
      placements: ["Reel", "Story", "Post"],
    },
    {
      id: "CMP-1143",
      title: "Kicks Holiday Routine Edit",
      range: "Nov 16, 2025 - Dec 08, 2025",
      placements: ["Reel", "Story"],
    },
  ],
  ongoing: [
    {
      id: "CMP-1238",
      title: "Adoore Spring Capsule Push",
      range: "Apr 05, 2026 - Apr 29, 2026",
      placements: ["Reel", "Post", "Story"],
    },
    {
      id: "CMP-1244",
      title: "Arla Protein Breakfast Moments",
      range: "Apr 08, 2026 - May 03, 2026",
      placements: ["Story", "Reel"],
    },
  ],
  suggested: [
    {
      id: "CMP-1261",
      title: "Caia Everyday Base Routine",
      range: "May 12, 2026 - Jun 01, 2026",
      placements: ["Reel", "Story"],
    },
    {
      id: "CMP-1268",
      title: "Weekday Denim Rotation",
      range: "May 19, 2026 - Jun 10, 2026",
      placements: ["Post", "Story"],
    },
  ],
};

const rankedCountry = [
  ["Sweden", "44.8%", 44.8],
  ["Norway", "13.3%", 13.3],
  ["Finland", "10.5%", 10.5],
  ["Germany", "8.7%", 8.7],
  ["Denmark", "6.1%", 6.1],
];

const rankedCity = [
  ["Stockholm", "18.4%", 18.4],
  ["Gothenburg", "8.9%", 8.9],
  ["Oslo", "7.1%", 7.1],
  ["Malmö", "5.8%", 5.8],
  ["Helsinki", "4.5%", 4.5],
];

const rankedLanguage = [
  ["Swedish", "61.2%", 61.2],
  ["English", "21.4%", 21.4],
  ["Norwegian", "8.3%", 8.3],
  ["Finnish", "3.9%", 3.9],
  ["German", "2.8%", 2.8],
];

const brandAffinity = [
  ["Adoore", "High affinity"],
  ["Caia Cosmetics", "High affinity"],
  ["NA-KD", "Medium affinity"],
  ["Kicks", "Medium affinity"],
  ["Matsmart", "Emerging"],
];

const interestAffinity = [
  ["Fashion & styling", "27.9%"],
  ["Beauty & skincare", "21.4%"],
  ["Home & lifestyle", "16.3%"],
  ["Travel", "9.2%"],
  ["Fitness", "8.8%"],
];

const lookalikes = [
  ["Hanna Friberg", "@hannafriberg", "197K", "4.7%", "9.3K"],
  ["Alice Stenlöf", "@alicestenlof", "408K", "3.8%", "14.1K"],
  ["Michaela Forni", "@michaelaforni", "356K", "3.2%", "8.9K"],
  ["Matilda Djerf", "@matildadjerf", "3.0M", "2.9%", "67K"],
];

const hashtags = ["#springlayers", "#skincareedit", "#nordicstyle", "#selfcare", "#weekendroutines", "#beautyfavorites"];
const mentions = ["@adoore", "@arlasverige", "@kicksse", "@caiacosmetics", "@weekdayofficial", "@lyko"];

const creatorTopicCloud = [
  { label: "soft glam", weight: 96 },
  { label: "capsule wardrobe", weight: 88 },
  { label: "morning routine", weight: 82 },
  { label: "Nordic style", weight: 76 },
  { label: "skin prep", weight: 70 },
  { label: "office outfits", weight: 64 },
  { label: "beauty empties", weight: 58 },
  { label: "city weekends", weight: 52 },
  { label: "neutral tailoring", weight: 46 },
  { label: "self care", weight: 40 },
  { label: "try-on haul", weight: 35 },
  { label: "clean base", weight: 30 },
];

const trendGenres = [
  "Fashion & beauty",
  "Fitness & health",
  "Gaming",
  "Tech",
  "Finance",
  "Travel",
  "Food",
  "Education",
  "Parenting",
  "Comedy",
];

const trendTopicCloudByGenre = {
  "Fashion & beauty": [
    { label: "capsule wardrobe", weight: 98 },
    { label: "clean girl makeup", weight: 88 },
    { label: "skin barrier", weight: 82 },
    { label: "spring layers", weight: 74 },
    { label: "lip combo", weight: 68 },
    { label: "quiet luxury", weight: 62 },
    { label: "GRWM", weight: 57 },
    { label: "hair gloss", weight: 50 },
    { label: "outfit rotation", weight: 44 },
    { label: "SPF routine", weight: 38 },
  ],
  "Fitness & health": [
    { label: "protein breakfast", weight: 96 },
    { label: "hybrid training", weight: 88 },
    { label: "steps challenge", weight: 79 },
    { label: "mobility", weight: 72 },
    { label: "sleep score", weight: 66 },
    { label: "meal prep", weight: 60 },
    { label: "Pilates", weight: 54 },
    { label: "recovery day", weight: 48 },
    { label: "zone 2", weight: 42 },
    { label: "hydration", weight: 36 },
  ],
  Gaming: [
    { label: "cozy gaming", weight: 94 },
    { label: "ranked climb", weight: 87 },
    { label: "patch notes", weight: 81 },
    { label: "creator codes", weight: 73 },
    { label: "boss guide", weight: 66 },
    { label: "loadout", weight: 60 },
    { label: "speedrun", weight: 54 },
    { label: "stream setup", weight: 47 },
    { label: "duo queue", weight: 41 },
    { label: "new season", weight: 35 },
  ],
  Tech: [
    { label: "AI workflow", weight: 97 },
    { label: "desk setup", weight: 88 },
    { label: "productivity stack", weight: 82 },
    { label: "wearables", weight: 74 },
    { label: "camera test", weight: 68 },
    { label: "app review", weight: 61 },
    { label: "automation", weight: 55 },
    { label: "creator tools", weight: 49 },
    { label: "battery life", weight: 42 },
    { label: "privacy", weight: 36 },
  ],
  Finance: [
    { label: "budget reset", weight: 95 },
    { label: "index funds", weight: 86 },
    { label: "salary transparency", weight: 80 },
    { label: "side income", weight: 73 },
    { label: "saving rate", weight: 66 },
    { label: "mortgage tips", weight: 59 },
    { label: "tax season", weight: 53 },
    { label: "portfolio check", weight: 47 },
    { label: "money habits", weight: 41 },
    { label: "debt payoff", weight: 34 },
  ],
  Travel: [
    { label: "city guide", weight: 97 },
    { label: "hotel review", weight: 88 },
    { label: "carry-on packing", weight: 80 },
    { label: "weekend trip", weight: 73 },
    { label: "hidden gems", weight: 67 },
    { label: "train travel", weight: 60 },
    { label: "food stops", weight: 54 },
    { label: "solo travel", weight: 48 },
    { label: "itinerary", weight: 42 },
    { label: "travel outfit", weight: 36 },
  ],
  Food: [
    { label: "high protein", weight: 96 },
    { label: "weeknight dinner", weight: 87 },
    { label: "air fryer", weight: 81 },
    { label: "meal prep", weight: 73 },
    { label: "grocery haul", weight: 67 },
    { label: "coffee routine", weight: 60 },
    { label: "one pan", weight: 54 },
    { label: "snack plate", weight: 47 },
    { label: "sourdough", weight: 41 },
    { label: "budget meals", weight: 35 },
  ],
  Education: [
    { label: "study routine", weight: 95 },
    { label: "exam prep", weight: 87 },
    { label: "language learning", weight: 80 },
    { label: "career switch", weight: 73 },
    { label: "note system", weight: 66 },
    { label: "microlearning", weight: 60 },
    { label: "AI tutor", weight: 54 },
    { label: "book summary", weight: 48 },
    { label: "course review", weight: 42 },
    { label: "focus blocks", weight: 36 },
  ],
  Parenting: [
    { label: "toddler meals", weight: 96 },
    { label: "sleep routine", weight: 88 },
    { label: "school run", weight: 79 },
    { label: "family travel", weight: 72 },
    { label: "sensory play", weight: 66 },
    { label: "nursery setup", weight: 60 },
    { label: "baby gear", weight: 54 },
    { label: "meal planning", weight: 48 },
    { label: "parenting hacks", weight: 42 },
    { label: "screen time", weight: 36 },
  ],
  Comedy: [
    { label: "POV skit", weight: 97 },
    { label: "relatable work", weight: 89 },
    { label: "dating stories", weight: 82 },
    { label: "family group chat", weight: 74 },
    { label: "voiceover", weight: 68 },
    { label: "duet format", weight: 61 },
    { label: "hot take", weight: 55 },
    { label: "character bit", weight: 49 },
    { label: "daily chaos", weight: 42 },
    { label: "trend audio", weight: 36 },
  ],
};

const trendStatsByGenre = Object.fromEntries(
  trendGenres.map((genre, genreIndex) => {
    const lift = genreIndex * 0.7;
    return [
      genre,
      [
        ["Followers", `${Math.round(96 + genreIndex * 11)}K`, `+${(2.4 + lift / 10).toFixed(1)}% sample`],
        ["Avg. Views", `${Math.round(31 + genreIndex * 3.4)}K`, `${Math.round(24 + genreIndex * 2)}K median`],
        ["View rate", `${(24.5 + genreIndex * 1.1).toFixed(1)}%`, "per post avg."],
        ["Avg. R. views", `${Math.round(52 + genreIndex * 4.6)}K`, "+8.2% trend"],
        ["R. view rate", `${(42.5 + genreIndex * 1.6).toFixed(1)}%`, "reels sample"],
        ["Avg. S. views", `${Math.round(14 + genreIndex * 1.8)}K`, "story avg."],
        ["S. view rate", `${(11.3 + genreIndex * 0.7).toFixed(1)}%`, "story sample"],
        ["Engagements", `${(5.8 + genreIndex * 0.6).toFixed(1)}K`, "+6.4% trend"],
        ["Engagement rate", `${(4.7 + genreIndex * 0.22).toFixed(1)}%`, "content avg."],
        ["Viewers eng. rate", `${(8.1 + genreIndex * 0.35).toFixed(1)}%`, "viewer avg."],
        ["Avg. likes", `${(4.6 + genreIndex * 0.45).toFixed(1)}K`, "+4.1% trend"],
        ["Avg. comm.", `${Math.round(92 + genreIndex * 9)}`, "per post"],
        ["Avg. shares", `${Math.round(210 + genreIndex * 22)}`, "+9.8% trend"],
        ["Avg. saves", `${Math.round(340 + genreIndex * 26)}`, "+7.5% trend"],
      ],
    ];
  })
);

const creatorResultPlatformOptions = [
  { id: "instagram", label: "Instagram", icon: "IG" },
  { id: "tiktok", label: "TikTok", icon: "TT" },
  { id: "youtube", label: "YouTube", icon: "YT" },
];

const creatorResultFilters = [
  "Bio & Caption",
  "Age",
  "Location",
  "Language",
  "Followers",
  "Engagement",
  "Views",
  "Gender",
  "Lookalikes",
  "Last Post",
  "Followers Growth",
  "Contact",
];

const fallbackTrendAudience = {
  locations: [
    ["Sweden", 34.2],
    ["United States", 18.6],
    ["United Kingdom", 11.4],
    ["Germany", 8.7],
    ["Norway", 6.9],
  ],
  genderSplit: { Female: 61, Male: 33, Other: 6 },
  genderByAge: [
    { group: "13-17", female: 5, male: 3 },
    { group: "18-24", female: 26, male: 14 },
    { group: "25-34", female: 30, male: 16 },
    { group: "35-44", female: 12, male: 7 },
    { group: "45-64", female: 5, male: 3 },
    { group: "65+", female: 1, male: 1 },
  ],
};

const trendAudienceByGenre = {
  "Fashion & beauty": {
    locations: [["Sweden", 31.8], ["France", 16.4], ["United Kingdom", 12.2], ["Germany", 9.5], ["Denmark", 6.8]],
    genderSplit: { Female: 74, Male: 21, Other: 5 },
    genderByAge: [
      { group: "13-17", female: 6, male: 1 },
      { group: "18-24", female: 32, male: 7 },
      { group: "25-34", female: 29, male: 9 },
      { group: "35-44", female: 10, male: 4 },
      { group: "45-64", female: 4, male: 2 },
      { group: "65+", female: 1, male: 0 },
    ],
  },
  "Fitness & health": {
    locations: [["United States", 28.2], ["Sweden", 17.5], ["United Kingdom", 12.8], ["Australia", 8.9], ["Norway", 6.4]],
    genderSplit: { Female: 57, Male: 39, Other: 4 },
    genderByAge: [
      { group: "13-17", female: 3, male: 2 },
      { group: "18-24", female: 21, male: 15 },
      { group: "25-34", female: 27, male: 17 },
      { group: "35-44", female: 11, male: 8 },
      { group: "45-64", female: 5, male: 4 },
      { group: "65+", female: 1, male: 1 },
    ],
  },
  Gaming: {
    locations: [["United States", 32.4], ["United Kingdom", 13.1], ["Germany", 10.7], ["Sweden", 7.9], ["Canada", 6.6]],
    genderSplit: { Female: 24, Male: 70, Other: 6 },
    genderByAge: [
      { group: "13-17", female: 5, male: 18 },
      { group: "18-24", female: 12, male: 36 },
      { group: "25-34", female: 8, male: 21 },
      { group: "35-44", female: 3, male: 7 },
      { group: "45-64", female: 1, male: 2 },
      { group: "65+", female: 0, male: 0 },
    ],
  },
  Tech: {
    locations: [["United States", 36.1], ["India", 14.8], ["United Kingdom", 10.1], ["Germany", 8.4], ["Sweden", 5.8]],
    genderSplit: { Female: 31, Male: 64, Other: 5 },
    genderByAge: [
      { group: "13-17", female: 2, male: 5 },
      { group: "18-24", female: 11, male: 24 },
      { group: "25-34", female: 16, male: 29 },
      { group: "35-44", female: 7, male: 13 },
      { group: "45-64", female: 3, male: 5 },
      { group: "65+", female: 1, male: 1 },
    ],
  },
  Finance: {
    locations: [["United States", 41.7], ["United Kingdom", 11.6], ["Canada", 7.8], ["Germany", 6.2], ["Sweden", 5.4]],
    genderSplit: { Female: 42, Male: 54, Other: 4 },
    genderByAge: [
      { group: "13-17", female: 1, male: 2 },
      { group: "18-24", female: 12, male: 18 },
      { group: "25-34", female: 21, male: 25 },
      { group: "35-44", female: 10, male: 12 },
      { group: "45-64", female: 5, male: 7 },
      { group: "65+", female: 1, male: 2 },
    ],
  },
  Travel: {
    locations: [["France", 18.9], ["United States", 17.4], ["Spain", 12.5], ["Italy", 11.7], ["Sweden", 8.2]],
    genderSplit: { Female: 63, Male: 32, Other: 5 },
    genderByAge: [
      { group: "13-17", female: 3, male: 1 },
      { group: "18-24", female: 24, male: 10 },
      { group: "25-34", female: 31, male: 15 },
      { group: "35-44", female: 12, male: 6 },
      { group: "45-64", female: 5, male: 3 },
      { group: "65+", female: 1, male: 1 },
    ],
  },
  Food: {
    locations: [["United States", 29.4], ["United Kingdom", 13.6], ["Sweden", 10.2], ["Italy", 8.5], ["France", 7.4]],
    genderSplit: { Female: 66, Male: 29, Other: 5 },
    genderByAge: [
      { group: "13-17", female: 4, male: 2 },
      { group: "18-24", female: 23, male: 9 },
      { group: "25-34", female: 28, male: 12 },
      { group: "35-44", female: 14, male: 7 },
      { group: "45-64", female: 7, male: 4 },
      { group: "65+", female: 2, male: 1 },
    ],
  },
  Education: {
    locations: [["United States", 30.2], ["India", 16.3], ["United Kingdom", 9.6], ["Canada", 7.1], ["Germany", 5.9]],
    genderSplit: { Female: 55, Male: 40, Other: 5 },
    genderByAge: [
      { group: "13-17", female: 7, male: 5 },
      { group: "18-24", female: 28, male: 19 },
      { group: "25-34", female: 17, male: 13 },
      { group: "35-44", female: 6, male: 5 },
      { group: "45-64", female: 2, male: 2 },
      { group: "65+", female: 0, male: 1 },
    ],
  },
  Parenting: {
    locations: [["United States", 25.6], ["Sweden", 16.7], ["United Kingdom", 13.2], ["Norway", 7.9], ["Canada", 6.1]],
    genderSplit: { Female: 78, Male: 18, Other: 4 },
    genderByAge: [
      { group: "13-17", female: 1, male: 0 },
      { group: "18-24", female: 12, male: 3 },
      { group: "25-34", female: 38, male: 8 },
      { group: "35-44", female: 25, male: 6 },
      { group: "45-64", female: 6, male: 2 },
      { group: "65+", female: 1, male: 1 },
    ],
  },
  Comedy: {
    locations: [["United States", 39.8], ["United Kingdom", 12.2], ["Canada", 8.1], ["Australia", 6.7], ["Germany", 5.3]],
    genderSplit: { Female: 49, Male: 45, Other: 6 },
    genderByAge: [
      { group: "13-17", female: 8, male: 7 },
      { group: "18-24", female: 25, male: 22 },
      { group: "25-34", female: 17, male: 16 },
      { group: "35-44", female: 5, male: 5 },
      { group: "45-64", female: 2, male: 2 },
      { group: "65+", female: 0, male: 1 },
    ],
  },
};

const fallbackCreatorResults = [
  {
    id: "cr-001",
    platform: "instagram",
    handle: "@linneastyle",
    name: "Linnea Holm",
    bio: "Stockholm creator covering capsule wardrobes, skincare routines, and clean Nordic styling.",
    avatarInitials: "LH",
    avatarTone: "warm",
    followers: 284000,
    avgViews: 118000,
    engagements: 14200,
    engagementRate: 5.1,
    viewersEngagementRate: 9.8,
    gender: "Female",
    contact: "Public email",
    lookalike: "Andrea Norrman",
    lastPost: "2 days ago",
    followersGrowth: 6.8,
    saved: false,
    matchTopics: ["Fashion & beauty", "capsule wardrobe", "skin barrier", "spring layers", "soft glam", "denim"],
  },
  {
    id: "cr-002",
    platform: "tiktok",
    handle: "@mealprepmaja",
    name: "Maja Lund",
    bio: "High-protein food prep, grocery hauls, and practical health routines for busy weeks.",
    avatarInitials: "ML",
    avatarTone: "green",
    followers: 412000,
    avgViews: 236000,
    engagements: 18800,
    engagementRate: 4.6,
    viewersEngagementRate: 8.2,
    gender: "Female",
    contact: "Agency",
    lookalike: "Food routine cluster",
    lastPost: "18 hours ago",
    followersGrowth: 8.3,
    saved: true,
    matchTopics: ["Food", "Fitness & health", "meal prep", "protein breakfast", "high protein", "grocery haul"],
  },
  {
    id: "cr-003",
    platform: "youtube",
    handle: "@techwithnoah",
    name: "Noah Berg",
    bio: "Desk setup reviews, AI workflow breakdowns, and creator productivity systems.",
    avatarInitials: "NB",
    avatarTone: "blue",
    followers: 198000,
    avgViews: 84000,
    engagements: 7300,
    engagementRate: 3.7,
    viewersEngagementRate: 6.5,
    gender: "Male",
    contact: "Public email",
    lookalike: "Tech workflow cluster",
    lastPost: "4 days ago",
    followersGrowth: 4.4,
    saved: false,
    matchTopics: ["Tech", "AI workflow", "desk setup", "productivity stack", "creator tools"],
  },
  {
    id: "cr-004",
    platform: "instagram",
    handle: "@travelsofella",
    name: "Ella Svan",
    bio: "Weekend city guides, boutique hotel reviews, and carry-on travel styling.",
    avatarInitials: "ES",
    avatarTone: "rose",
    followers: 176000,
    avgViews: 62000,
    engagements: 6900,
    engagementRate: 3.9,
    viewersEngagementRate: 7.4,
    gender: "Female",
    contact: "DM only",
    lookalike: "Nordic travel cluster",
    lastPost: "1 day ago",
    followersGrowth: 3.2,
    saved: false,
    matchTopics: ["Travel", "city guide", "hotel review", "weekend trip", "travel outfit"],
  },
  {
    id: "cr-005",
    platform: "tiktok",
    handle: "@rankedrasmus",
    name: "Rasmus K",
    bio: "Gaming patches, ranked climb clips, loadout tests, and creator-code performance.",
    avatarInitials: "RK",
    avatarTone: "dark",
    followers: 522000,
    avgViews: 318000,
    engagements: 24600,
    engagementRate: 4.7,
    viewersEngagementRate: 7.9,
    gender: "Male",
    contact: "Agency",
    lookalike: "Gaming clips cluster",
    lastPost: "9 hours ago",
    followersGrowth: 11.6,
    saved: false,
    matchTopics: ["Gaming", "ranked climb", "patch notes", "loadout", "new season"],
  },
  {
    id: "cr-006",
    platform: "youtube",
    handle: "@financewithfreja",
    name: "Freja Nyström",
    bio: "Simple budget resets, index fund explainers, and salary transparency conversations.",
    avatarInitials: "FN",
    avatarTone: "neutral",
    followers: 151000,
    avgViews: 54000,
    engagements: 4800,
    engagementRate: 3.2,
    viewersEngagementRate: 5.9,
    gender: "Female",
    contact: "Public email",
    lookalike: "Finance education cluster",
    lastPost: "6 days ago",
    followersGrowth: 2.9,
    saved: false,
    matchTopics: ["Finance", "budget reset", "index funds", "saving rate", "money habits", "Education"],
  },
  {
    id: "cr-007",
    platform: "instagram",
    handle: "@pilatesjulia",
    name: "Julia Ek",
    bio: "Pilates routines, recovery days, mobility clips, and realistic wellness habits.",
    avatarInitials: "JE",
    avatarTone: "green",
    followers: 228000,
    avgViews: 92000,
    engagements: 10100,
    engagementRate: 4.4,
    viewersEngagementRate: 8.7,
    gender: "Female",
    contact: "Management",
    lookalike: "Wellness routines cluster",
    lastPost: "3 days ago",
    followersGrowth: 5.5,
    saved: true,
    matchTopics: ["Fitness & health", "Pilates", "mobility", "recovery day", "hydration"],
  },
  {
    id: "cr-008",
    platform: "tiktok",
    handle: "@skitsbysam",
    name: "Sam Ortega",
    bio: "Fast POV skits, dating stories, and relatable work comedy with trend-audio hooks.",
    avatarInitials: "SO",
    avatarTone: "purple",
    followers: 734000,
    avgViews: 486000,
    engagements: 36500,
    engagementRate: 5,
    viewersEngagementRate: 8.9,
    gender: "Non-binary",
    contact: "Agency",
    lookalike: "Comedy POV cluster",
    lastPost: "12 hours ago",
    followersGrowth: 13.2,
    saved: false,
    matchTopics: ["Comedy", "POV skit", "relatable work", "dating stories", "trend audio"],
  },
  {
    id: "cr-009",
    platform: "youtube",
    handle: "@learnwithalma",
    name: "Alma Chen",
    bio: "Study systems, AI tutor experiments, book summaries, and practical exam prep.",
    avatarInitials: "AC",
    avatarTone: "blue",
    followers: 268000,
    avgViews: 102000,
    engagements: 8200,
    engagementRate: 3.1,
    viewersEngagementRate: 6.1,
    gender: "Female",
    contact: "Public email",
    lookalike: "Education creator cluster",
    lastPost: "5 days ago",
    followersGrowth: 4.9,
    saved: false,
    matchTopics: ["Education", "study routine", "AI tutor", "book summary", "focus blocks"],
  },
  {
    id: "cr-010",
    platform: "instagram",
    handle: "@familywithnora",
    name: "Nora Lind",
    bio: "Toddler meals, school-run organization, family travel, and practical parenting hacks.",
    avatarInitials: "NL",
    avatarTone: "warm",
    followers: 193000,
    avgViews: 69000,
    engagements: 6200,
    engagementRate: 3.2,
    viewersEngagementRate: 6.9,
    gender: "Female",
    contact: "DM only",
    lookalike: "Parenting lifestyle cluster",
    lastPost: "2 days ago",
    followersGrowth: 3.7,
    saved: false,
    matchTopics: ["Parenting", "toddler meals", "family travel", "parenting hacks", "meal planning"],
  },
  {
    id: "cr-011",
    platform: "instagram",
    handle: "@denimdiary",
    name: "Sara Voss",
    bio: "Denim rotations, outfit formulas, try-on hauls, and minimal wardrobe edits.",
    avatarInitials: "SV",
    avatarTone: "neutral",
    followers: 319000,
    avgViews: 141000,
    engagements: 15800,
    engagementRate: 5,
    viewersEngagementRate: 9.4,
    gender: "Female",
    contact: "Public email",
    lookalike: "Capsule wardrobe cluster",
    lastPost: "1 day ago",
    followersGrowth: 7.1,
    saved: false,
    matchTopics: ["Fashion & beauty", "denim", "outfit rotation", "try-on haul", "capsule wardrobe"],
  },
  {
    id: "cr-012",
    platform: "youtube",
    handle: "@homecookhenrik",
    name: "Henrik Dahl",
    bio: "One-pan dinners, budget meals, sourdough tests, and approachable weeknight food.",
    avatarInitials: "HD",
    avatarTone: "warm",
    followers: 127000,
    avgViews: 47000,
    engagements: 3900,
    engagementRate: 3.1,
    viewersEngagementRate: 5.7,
    gender: "Male",
    contact: "Public email",
    lookalike: "Home cooking cluster",
    lastPost: "1 week ago",
    followersGrowth: 2.4,
    saved: false,
    matchTopics: ["Food", "weeknight dinner", "one pan", "sourdough", "budget meals"],
  },
  {
    id: "cr-013",
    platform: "tiktok",
    handle: "@glossbygreta",
    name: "Greta Falk",
    bio: "Lip combos, hair gloss tests, and fast GRWM edits for beauty-led shopping moments.",
    avatarInitials: "GF",
    avatarTone: "rose",
    followers: 388000,
    avgViews: 224000,
    engagements: 17600,
    engagementRate: 4.5,
    viewersEngagementRate: 8.1,
    gender: "Female",
    contact: "Agency",
    lookalike: "Beauty GRWM cluster",
    lastPost: "16 hours ago",
    followersGrowth: 9.2,
    saved: false,
    matchTopics: ["Fashion & beauty", "clean girl makeup", "lip combo", "hair gloss", "GRWM"],
  },
  {
    id: "cr-014",
    platform: "youtube",
    handle: "@mobilitymarcus",
    name: "Marcus Ali",
    bio: "Mobility routines, zone 2 training explainers, and recovery-first fitness programming.",
    avatarInitials: "MA",
    avatarTone: "green",
    followers: 211000,
    avgViews: 76000,
    engagements: 6600,
    engagementRate: 3.1,
    viewersEngagementRate: 6.2,
    gender: "Male",
    contact: "Public email",
    lookalike: "Hybrid training cluster",
    lastPost: "3 days ago",
    followersGrowth: 4.8,
    saved: false,
    matchTopics: ["Fitness & health", "hybrid training", "zone 2", "mobility", "recovery day"],
  },
  {
    id: "cr-015",
    platform: "instagram",
    handle: "@aiautomationida",
    name: "Ida Lindqvist",
    bio: "AI workflow templates, app reviews, automation demos, and creator tool comparisons.",
    avatarInitials: "IL",
    avatarTone: "blue",
    followers: 246000,
    avgViews: 96000,
    engagements: 9100,
    engagementRate: 3.7,
    viewersEngagementRate: 6.8,
    gender: "Female",
    contact: "Management",
    lookalike: "AI productivity cluster",
    lastPost: "2 days ago",
    followersGrowth: 8.7,
    saved: false,
    matchTopics: ["Tech", "AI workflow", "automation", "app review", "creator tools"],
  },
  {
    id: "cr-016",
    platform: "tiktok",
    handle: "@salarysimon",
    name: "Simon Reed",
    bio: "Salary transparency, debt payoff explainers, and quick money habit breakdowns.",
    avatarInitials: "SR",
    avatarTone: "neutral",
    followers: 354000,
    avgViews: 181000,
    engagements: 12800,
    engagementRate: 3.6,
    viewersEngagementRate: 6.4,
    gender: "Male",
    contact: "Agency",
    lookalike: "Finance short-form cluster",
    lastPost: "22 hours ago",
    followersGrowth: 7.9,
    saved: false,
    matchTopics: ["Finance", "salary transparency", "debt payoff", "money habits", "budget reset"],
  },
  {
    id: "cr-017",
    platform: "instagram",
    handle: "@carryonclara",
    name: "Clara Möller",
    bio: "Carry-on packing, train travel itineraries, and city outfit ideas for short trips.",
    avatarInitials: "CM",
    avatarTone: "warm",
    followers: 241000,
    avgViews: 88000,
    engagements: 9400,
    engagementRate: 3.9,
    viewersEngagementRate: 7.3,
    gender: "Female",
    contact: "Public email",
    lookalike: "Travel outfit cluster",
    lastPost: "2 days ago",
    followersGrowth: 5.1,
    saved: false,
    matchTopics: ["Travel", "carry-on packing", "train travel", "itinerary", "travel outfit"],
  },
  {
    id: "cr-018",
    platform: "tiktok",
    handle: "@airfryeramina",
    name: "Amina Said",
    bio: "Air fryer dinners, snack plates, and high-protein weeknight meals with grocery hooks.",
    avatarInitials: "AS",
    avatarTone: "green",
    followers: 469000,
    avgViews: 264000,
    engagements: 21300,
    engagementRate: 4.5,
    viewersEngagementRate: 8.4,
    gender: "Female",
    contact: "Agency",
    lookalike: "Food short-form cluster",
    lastPost: "11 hours ago",
    followersGrowth: 10.4,
    saved: false,
    matchTopics: ["Food", "air fryer", "snack plate", "high protein", "weeknight dinner"],
  },
  {
    id: "cr-019",
    platform: "instagram",
    handle: "@notionnotesneo",
    name: "Neo Park",
    bio: "Note systems, focus blocks, language learning dashboards, and study routine templates.",
    avatarInitials: "NP",
    avatarTone: "purple",
    followers: 184000,
    avgViews: 59000,
    engagements: 6100,
    engagementRate: 3.3,
    viewersEngagementRate: 6.3,
    gender: "Non-binary",
    contact: "DM only",
    lookalike: "Study systems cluster",
    lastPost: "4 days ago",
    followersGrowth: 4.1,
    saved: false,
    matchTopics: ["Education", "note system", "language learning", "study routine", "focus blocks"],
  },
  {
    id: "cr-020",
    platform: "youtube",
    handle: "@screenwiseeva",
    name: "Eva Brandt",
    bio: "Screen time routines, school-run systems, baby gear reviews, and family planning content.",
    avatarInitials: "EB",
    avatarTone: "rose",
    followers: 138000,
    avgViews: 42000,
    engagements: 3600,
    engagementRate: 2.6,
    viewersEngagementRate: 5.2,
    gender: "Female",
    contact: "Public email",
    lookalike: "Parenting practical cluster",
    lastPost: "1 week ago",
    followersGrowth: 2.6,
    saved: false,
    matchTopics: ["Parenting", "screen time", "baby gear", "school run", "parenting hacks"],
  },
  {
    id: "cr-021",
    platform: "instagram",
    handle: "@povpetra",
    name: "Petra Sol",
    bio: "Character bits, daily chaos edits, hot takes, and workplace POV formats.",
    avatarInitials: "PS",
    avatarTone: "dark",
    followers: 296000,
    avgViews: 133000,
    engagements: 11900,
    engagementRate: 4,
    viewersEngagementRate: 7.1,
    gender: "Female",
    contact: "Management",
    lookalike: "POV comedy cluster",
    lastPost: "1 day ago",
    followersGrowth: 8.1,
    saved: false,
    matchTopics: ["Comedy", "character bit", "daily chaos", "hot take", "POV skit"],
  },
  {
    id: "cr-022",
    platform: "youtube",
    handle: "@streamsetupstefan",
    name: "Stefan Nyberg",
    bio: "Stream setup guides, boss strategy breakdowns, and new season gaming explainers.",
    avatarInitials: "SN",
    avatarTone: "blue",
    followers: 162000,
    avgViews: 72000,
    engagements: 5700,
    engagementRate: 3.5,
    viewersEngagementRate: 6,
    gender: "Male",
    contact: "Public email",
    lookalike: "Gaming guide cluster",
    lastPost: "5 days ago",
    followersGrowth: 3.8,
    saved: false,
    matchTopics: ["Gaming", "stream setup", "boss guide", "new season", "creator codes"],
  },
];

const creatorResultsByGenre = Object.fromEntries(
  trendGenres.map((genre) => [
    genre,
    fallbackCreatorResults.filter((creator) => creator.matchTopics.includes(genre)),
  ])
);

const trendCards = [
  { title: "Followers", value: "124.7K", note: "+2.8% this month", color: "#6f3cc3", points: [14, 18, 21, 22, 28, 31, 36] },
  { title: "Following", value: "1,294", note: "+0.6% this month", color: "#3b82f6", points: [20, 22, 19, 24, 26, 28, 30] },
  { title: "Likes", value: "5.9K", note: "+5.4% this month", color: "#1ca67a", points: [10, 15, 14, 20, 19, 26, 29] },
];

const contentItems = [
  {
    type: "Reel",
    date: "Apr 12",
    title: "Morning skin prep and soft glam base",
    subtitle: "Sponsored by Caia Cosmetics",
    brand: "Caia",
    views: "124K",
    likes: "8.2K",
    comments: "182",
    sponsored: true,
    video: true,
    gradient:
      "linear-gradient(180deg, rgba(0,0,0,0.06), rgba(0,0,0,0.14)), radial-gradient(circle at 30% 20%, #e8d7d1 0%, #c79b87 34%, #6b4a46 72%, #2f2427 100%)",
  },
  {
    type: "Post",
    date: "Apr 09",
    title: "Neutral tailoring for spring meetings",
    subtitle: "Organic fashion content",
    brand: "",
    views: "48K",
    likes: "4.4K",
    comments: "73",
    sponsored: false,
    video: false,
    gradient:
      "linear-gradient(180deg, rgba(0,0,0,0.04), rgba(0,0,0,0.1)), radial-gradient(circle at 60% 18%, #f0e3d2 0%, #c0aa91 36%, #84705e 71%, #383238 100%)",
  },
  {
    type: "Reel",
    date: "Apr 07",
    title: "Protein breakfast routine before shoot day",
    subtitle: "Sponsored by Arla Protein",
    brand: "Arla",
    views: "91K",
    likes: "6.8K",
    comments: "144",
    sponsored: true,
    video: true,
    gradient:
      "linear-gradient(180deg, rgba(0,0,0,0.04), rgba(0,0,0,0.12)), radial-gradient(circle at 34% 20%, #f3e7cf 0%, #d6c39b 28%, #6c6f6d 66%, #262a2c 100%)",
  },
  {
    type: "Story",
    date: "Apr 05",
    title: "Three-link outfit poll sequence",
    subtitle: "Sponsored story set",
    brand: "Adoore",
    views: "34K",
    likes: "2.2K",
    comments: "41",
    sponsored: true,
    video: false,
    gradient:
      "linear-gradient(180deg, rgba(0,0,0,0.04), rgba(0,0,0,0.12)), radial-gradient(circle at 70% 15%, #f2d6dc 0%, #cc8ca1 32%, #816277 68%, #2d2631 100%)",
  },
  {
    type: "Reel",
    date: "Apr 03",
    title: "Day-to-night makeup in one routine",
    subtitle: "Organic beauty content",
    brand: "",
    views: "73K",
    likes: "5.1K",
    comments: "97",
    sponsored: false,
    video: true,
    gradient:
      "linear-gradient(180deg, rgba(0,0,0,0.03), rgba(0,0,0,0.13)), radial-gradient(circle at 46% 25%, #f1dfd9 0%, #dcb5ad 28%, #8f6564 63%, #2f272d 100%)",
  },
  {
    type: "Post",
    date: "Mar 31",
    title: "Desk setup and planning ritual",
    subtitle: "Lifestyle post",
    brand: "",
    views: "27K",
    likes: "2.8K",
    comments: "58",
    sponsored: false,
    video: false,
    gradient:
      "linear-gradient(180deg, rgba(0,0,0,0.03), rgba(0,0,0,0.12)), radial-gradient(circle at 50% 15%, #ede2d5 0%, #c7b8a4 33%, #89827b 68%, #2d3035 100%)",
  },
  {
    type: "Reel",
    date: "Mar 28",
    title: "Weekend city guide and cafe stops",
    subtitle: "Travel-focused content",
    brand: "",
    views: "66K",
    likes: "4.7K",
    comments: "88",
    sponsored: false,
    video: true,
    gradient:
      "linear-gradient(180deg, rgba(0,0,0,0.03), rgba(0,0,0,0.12)), radial-gradient(circle at 25% 18%, #d7e0ec 0%, #8fa7bd 33%, #5d6f88 63%, #26313f 100%)",
  },
  {
    type: "Post",
    date: "Mar 25",
    title: "Layered neutrals and oversized outerwear",
    subtitle: "Sponsored by Weekday",
    brand: "Weekday",
    views: "39K",
    likes: "3.6K",
    comments: "76",
    sponsored: true,
    video: false,
    gradient:
      "linear-gradient(180deg, rgba(0,0,0,0.04), rgba(0,0,0,0.12)), radial-gradient(circle at 40% 15%, #e8dbc9 0%, #bea68a 36%, #746252 68%, #262326 100%)",
  },
  {
    type: "Reel",
    date: "Mar 21",
    title: "Five beauty products I actually repurchase",
    subtitle: "Organic beauty content",
    brand: "",
    views: "118K",
    likes: "9.1K",
    comments: "201",
    sponsored: false,
    video: true,
    gradient:
      "linear-gradient(180deg, rgba(0,0,0,0.03), rgba(0,0,0,0.12)), radial-gradient(circle at 52% 20%, #f2ddcf 0%, #d4af96 32%, #8f6f61 67%, #2d2530 100%)",
  },
  {
    type: "Story",
    date: "Mar 18",
    title: "Poll sticker and try-on story sequence",
    subtitle: "Sponsored by Kicks",
    brand: "Kicks",
    views: "29K",
    likes: "1.6K",
    comments: "22",
    sponsored: true,
    video: false,
    gradient:
      "linear-gradient(180deg, rgba(0,0,0,0.03), rgba(0,0,0,0.12)), radial-gradient(circle at 48% 14%, #e4d7ea 0%, #b7a0c7 28%, #675c86 60%, #252330 100%)",
  },
];
