export const state = {
  globalView: "trend-exploration",
  view: "statistics",
  collaborations: "ongoing",
  audienceMetric: "followers",
  contentSort: "impressions",
  contentScope: "all",
  trendMode: "genre",
  activeTrendBoardId: "main",
  selectedGenre: "Fashion & beauty",
  trendSearch: "",
  customTrendBoards: [],
  activeTopic: { scope: "creator", label: "" },
  creatorResultSearch: "",
  creatorResultPlatforms: ["instagram", "tiktok", "youtube"],
  creatorResultFilters: [],
  creatorResultSort: "engagements",
  savedCreatorIds: ["cr-002", "cr-007"],
  addedCreatorIds: [],
  topicCloudEdits: {},
};
