export const state = {
  globalView: "trend-exploration",
  view: "statistics",
  collaborations: "ongoing",
  audienceMetric: "followers",
  contentSort: "impressions",
  contentScope: "all",
  trendMode: "genre",
  activeTrendBoardId: "demo-breakfast",
  selectedGenre: "Food",
  trendSearch: "",
  emergingKeywordSearch: "",
  emergingKeywordSource: "all",
  emergingKeywordPlatform: "all",
  customTrendBoards: [
    {
      id: "demo-breakfast",
      name: "Breakfast",
      keywords: [
        "breakfast",
        "protein breakfast",
        "coffee routine",
        "meal prep",
        "high protein",
        "grocery haul",
      ],
      referenceCreatorIds: ["ref-leanne", "ref-mayafood"],
      creatorSearch: "",
    },
  ],
  activeTopic: { scope: "creator", label: "" },
  creatorResultSearch: "",
  creatorResultPlatforms: ["instagram", "tiktok", "youtube"],
  creatorResultFilters: [],
  creatorResultSort: "engagements",
  savedCreatorIds: ["cr-002", "cr-007"],
  addedCreatorIds: [],
  topicCloudEdits: {},
};
